@Host = https://localhost:7221
@Route = {{Host}}/api/News

POST {{Route}}/add-news
Content-Type: application/json

{
  "title": "خبر شماره 2",
  "description": "توضیحات مربوط به خبر شماره 2",
  "body": "توضیحات مربوط به خبر شماره توضیحات مربوط به خبر شماره توضیحات مربوط به خبر شماره توضیحات مربوط به خبر شماره توضیحات مربوط به خبر شماره توضیحات مربوط به خبر شماره توضیحات مربوط به خبر شماره توضیحات مربوط به خبر شمت مرحات مربوط به خبر شماره ",
  "keywords": [
    "028B561B-4D08-4B53-A326-95CC243AFE41"
  ]
}
######################

PUT {{Route}}/edit-news
Content-Type: application/json

{
  "Code" : "34B2B112-3FCC-45E4-9459-D8500B64D6B8",
  "title": "خبر شماره 3000",
  "description": "توضیحات مربوط به خبر شماره 30000",
  "body": "توضیحات مربوط به خبر شماره توضیحات مربوط به خبر شماره توضیحات مربوط به خبر شماره توضیحات مربوط به خبر شماره توضیحات مربوط به خبر شماره توضیحات مربوط به خبر شماره توضیحات مربوط به خبر شماره توضیحات مربوط به خبر شمت مرحات مربوط به خبر شماره ",
  "keywords": [
    "028B561B-4D08-4B53-A326-95CC243AFE41"
  ]
}
######################

DELETE {{Route}}/delete-news
Content-Type: application/json

{
  "Code" : "2563f366-efa9-41ef-9f68-d656425ef86a"
}
######################

GET {{Route}}/
Content-Type: application/json

{
  "page": 1,
  "size": 1,
  "sortAscending": false,
  "sortBy": "Id",
  "neededTotalCount": true,
  "title": "خبر شماره"
}
######################
